# fly.toml file generated for outdoor-heart-sutra-backend on 2023-04-12T20:31:41+09:00

app = "outdoor-heart-sutra-backend"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "nrt"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
