# fly.toml app configuration file generated for outdoor-heart-sutra-backend on 2023-08-04T21:43:21+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "outdoor-heart-sutra-backend"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
