name: "Frontend Test"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: ./frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Run unit tests
        run: npx jest
        working-directory: ./frontend
      - name: Archive screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: ./frontend/playwright/screenshots
        if: always()
