name: "Frontend Test And Lint"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  e2e-tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: "3.2.1"
          bundler-cache: true
      - name: Install dependencies
        run: |
          cd backend
          bundle install
      - name: Set up database schema
        run: bin/rails db:schema:load
        working-directory: ./backend
      - name: Start Rails API server
        run: |
          cd backend
          bundle exec rails s -e test -p 3000 &
        env:
          RAILS_ENV: test
      - name: Wait for Rails API server to be ready
        run: sleep 15

        
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./frontend

      - name: Start frontend server
        run: npm run dev &
        working-directory: ./frontend

      - name: Wait for server to be ready
        run: sleep 30

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ./frontend/playwright
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30


  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Prettier
        run: npm run format
        working-directory: ./frontend
      - name: Lint
        run: npm run lint
        working-directory: ./frontend
